# Machine learning

In [2]:
%pip install sqlalchemy
from sqlalchemy import create_engine
%pip install pandas
%pip install pymysql

import pandas as pd

# Database connection URL
database_url = 'mysql+pymysql://360556_root:hackathonipssi*@mysql-hackathonipssi.alwaysdata.net/hackathonipssi_mia4'

# Create a database engine
engine = create_engine(database_url)

# Connect to the database and read tables
try:
    connection = engine.connect()
    df_athletes = pd.read_sql_table('Athlete', con=connection)
    df_hosts = pd.read_sql_table('Host', con=connection)
    df_medals = pd.read_sql_table('Medal', con=connection)
    df_results = pd.read_sql_table('Result', con=connection)
    print("Athlete Data:\n", df_athletes.head())
    print("Host Data:\n", df_hosts.head())
    print("Medal Data:\n", df_medals.head())
    print("Result Data:\n", df_results.head())
finally:
    connection.close()  # Always close the connection
pd.DataFrame(df_hosts)

# clean_and_convert(df_hosts)
# clean_and_convert(df_athletes)
# clean_and_convert(df_results)
# clean_and_convert(df_medals)

Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.12.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pymysql in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Athlete Data:
                                          athlete_url     athlete_full_name
0  https://olympics.com/en/athletes/a-aziz-hassan...  A-Aziz Hassan JALOOF  \
1    https://olympics.com/en/athletes/a-baser-wasiqi        A Baser WASIQI
2          https://olympics.com/en/athletes/a-darnis             A. DARNIS
3  https://olympics.com/en/athletes/a-germaine-go...   A. Germaine GOLDING
4          https://olympics.com/en/athletes/a-j-hurt              A J HURT

   games_participations      first_game  athlete_year_birth athlete_medals
0                   2.0  Barcelona 1992              1973.0           None  \
1                   1.0    Atlanta 1996              1975.0           None
2                   1.0      Paris 1900                 0.0           None
3                   1.0      Paris 1924              1887.0           None
4                   1.0    Beijing 2022              2000.0           None

                                                 bio
0                                               None
1    \n\n\nPersonal Best: Mar â€“ unknown.\n\n\n\n\n\n
2                                               None
3  \n\n\nGermaine Golding was a top French player...
4                                               None
Host Data:
           game_slug       game_end_date     game_start_date game_location
0  albertville-1992 1992-02-23 19:00:00 1992-02-08 07:00:00        France  \
1    amsterdam-1928 1928-08-12 19:00:00 1928-05-17 07:00:00   Netherlands
2      antwerp-1920 1920-09-12 19:00:00 1920-04-20 07:00:00       Belgium
3       athens-1896 1896-04-15 11:39:39 1896-04-06 11:38:39        Greece
4       athens-2004 2004-08-29 18:00:00 2004-08-13 06:00:00        Greece

          game_name game_season  game_year
0  Albertville 1992      Winter       1992
1    Amsterdam 1928      Summer       1928
2      Antwerp 1920      Summer       1920
3       Athens 1896      Summer       1896
4       Athens 2004      Summer       2004
Medal Data:
    id discipline_title     slug_game    event_title event_gender medal_type
0   1          Curling  beijing-2022  Mixed Doubles        Mixed       GOLD  \
1   2          Curling  beijing-2022  Mixed Doubles        Mixed       GOLD
2   3          Curling  beijing-2022  Mixed Doubles        Mixed     SILVER
3   4          Curling  beijing-2022  Mixed Doubles        Mixed     SILVER
4   5          Curling  beijing-2022  Mixed Doubles        Mixed     BRONZE

  participant_type participant_title
0         GameTeam             Italy  \
1         GameTeam             Italy
2         GameTeam            Norway
3         GameTeam            Norway
4         GameTeam            Sweden

                                         athlete_url     athlete_full_name
0  https://olympics.com/en/athletes/stefania-cons...  Stefania CONSTANTINI  \
1      https://olympics.com/en/athletes/amos-mosaner          Amos MOSANER
2  https://olympics.com/en/athletes/kristin-skaslien      Kristin SKASLIEN
3  https://olympics.com/en/athletes/magnus-nedreg...    Magnus NEDREGOTTEN
4     https://olympics.com/en/athletes/almida-de-val         Almida DE VAL

  country_name country_code country_3_letter_code
0        Italy           IT                   ITA
1        Italy           IT                   ITA
2       Norway           NO                   NOR
3       Norway           NO                   NOR
4       Sweden           SE                   SWE
Result Data:
    id discipline_title    event_title     slug_game participant_type
0   1          Curling  Mixed Doubles  beijing-2022         GameTeam  \
1   2          Curling  Mixed Doubles  beijing-2022         GameTeam
2   3          Curling  Mixed Doubles  beijing-2022         GameTeam
3   4          Curling  Mixed Doubles  beijing-2022         GameTeam
4   5          Curling  Mixed Doubles  beijing-2022         GameTeam

  medal_type rank_equal rank_position   country_name country_code
0       GOLD          0             1          Italy           IT  \
1     SILVER          0             2         Norway           NO
2     BRONZE          0             3         Sweden           SE
3       None          0             4  Great Britain           GB
4       None          0             5         Canada           CA

  country_3_letter_code                                        athlete_url
0                   ITA  https://olympics.com/en/athletes/stefania-cons...  \
1                   NOR  https://olympics.com/en/athletes/kristin-skaslien
2                   SWE     https://olympics.com/en/athletes/almida-de-val
3                   GBR    https://olympics.com/en/athletes/jennifer-dodds
4                   CAN      https://olympics.com/en/athletes/rachel-homan

      athlete_full_name value_unit value_type    athlete_full_name1
0  Stefania CONSTANTINI       None       None  Stefania CONSTANTINI  \
1      Kristin SKASLIEN       None       None      Kristin SKASLIEN
2         Almida DE VAL       None       None         Almida DE VAL
3        Jennifer DODDS       None       None        Jennifer DODDS
4          Rachel HOMAN       None       None          Rachel HOMAN

                                        athlete_url1  athlete_full_name2
0  https://olympics.com/en/athletes/stefania-cons...        Amos MOSANER  \
1  https://olympics.com/en/athletes/kristin-skaslien  Magnus NEDREGOTTEN
2     https://olympics.com/en/athletes/almida-de-val      Oskar ERIKSSON
3    https://olympics.com/en/athletes/jennifer-dodds         Bruce MOUAT
4      https://olympics.com/en/athletes/rachel-homan         John MORRIS

                                        athlete_url2
0      https://olympics.com/en/athletes/amos-mosaner
1  https://olympics.com/en/athletes/magnus-nedreg...
2    https://olympics.com/en/athletes/oskar-eriksson
3       https://olympics.com/en/athletes/bruce-mouat
4       https://olympics.com/en/athletes/john-morris

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,albertville-1992,1992-02-23 19:00:00,1992-02-08 07:00:00,France,Albertville 1992,Winter,1992
1,amsterdam-1928,1928-08-12 19:00:00,1928-05-17 07:00:00,Netherlands,Amsterdam 1928,Summer,1928
2,antwerp-1920,1920-09-12 19:00:00,1920-04-20 07:00:00,Belgium,Antwerp 1920,Summer,1920
3,athens-1896,1896-04-15 11:39:39,1896-04-06 11:38:39,Greece,Athens 1896,Summer,1896
4,athens-2004,2004-08-29 18:00:00,2004-08-13 06:00:00,Greece,Athens 2004,Summer,2004
5,atlanta-1996,1996-08-05 21:00:00,1996-07-19 12:00:00,United States,Atlanta 1996,Summer,1996
6,barcelona-1992,1992-08-09 18:00:00,1992-07-25 06:00:00,Spain,Barcelona 1992,Summer,1992
7,beijing-2008,2008-08-24 12:00:00,2008-08-08 00:00:00,China,Beijing 2008,Summer,2008
8,beijing-2022,2022-02-20 12:00:00,2022-02-04 15:00:00,China,Beijing 2022,Winter,2022
9,berlin-1936,1936-08-16 19:00:00,1936-08-01 07:00:00,Germany,Berlin 1936,Summer,1936
10,calgary-1988,1988-02-28 03:00:00,1988-02-13 15:00:00,Canada,Calgary 1988,Winter,1988
11,chamonix-1924,1924-02-05 20:00:00,1924-01-25 08:00:00,France,Chamonix 1924,Winter,1924
12,cortina-d-ampezzo-1956,1956-02-05 19:00:00,1956-01-26 07:00:00,Italy,Cortina d'Ampezzo 1956,Winter,1956
13,garmisch-partenkirchen-1936,1936-02-16 20:00:00,1936-02-06 08:00:00,Germany,Garmisch-Partenkirchen 1936,Winter,1936
14,grenoble-1968,1968-02-18 19:00:00,1968-02-06 07:00:00,France,Grenoble 1968,Winter,1968
15,helsinki-1952,1952-08-03 07:00:00,1952-07-19 07:00:00,Finland,Helsinki 1952,Summer,1952
16,innsbruck-1964,1964-02-09 19:00:00,1964-01-29 07:00:00,Austria,Innsbruck 1964,Winter,1964
17,innsbruck-1976,1976-02-15 19:00:00,1976-02-04 07:00:00,Austria,Innsbruck 1976,Winter,1976
18,lake-placid-1932,1932-02-15 18:00:00,1932-02-04 13:00:00,United States,Lake Placid 1932,Winter,1932
19,lake-placid-1980,1980-02-24 01:00:00,1980-02-13 13:00:00,United States,Lake Placid 1980,Winter,1980
20,lillehammer-1994,1994-02-27 19:00:00,1994-02-12 07:00:00,Norway,Lillehammer 1994,Winter,1994
21,london-1908,1908-10-31 20:09:00,1908-04-27 08:00:00,Great Britain,London 1908,Summer,1908
22,london-1948,1948-08-14 19:00:00,1948-07-29 07:00:00,Great Britain,London 1948,Summer,1948
23,london-2012,2012-08-12 19:00:00,2012-07-27 07:00:00,Great Britain,London 2012,Summer,2012
24,los-angeles-1932,1932-08-14 19:00:00,1932-07-30 16:00:00,United States,Los Angeles 1932,Summer,1932
25,los-angeles-1984,1984-08-12 19:00:00,1984-07-28 15:00:00,United States,Los Angeles 1984,Summer,1984
26,melbourne-1956,1956-12-08 10:00:00,1956-11-21 22:00:00,"Australia, Sweden",Melbourne 1956,Summer,1956
27,mexico-city-1968,1968-10-28 04:00:00,1968-10-12 16:00:00,Mexico,Mexico City 1968,Summer,1968
28,montreal-1976,1976-07-31 22:00:00,1976-07-17 12:00:00,Canada,Montreal 1976,Summer,1976
29,moscow-1980,1980-08-03 18:00:00,1980-07-19 05:00:00,USSR,Moscow 1980,Summer,1980
30,munich-1972,1972-09-11 19:00:00,1972-08-26 07:00:00,Federal Republic of Germany,Munich 1972,Summer,1972
31,nagano-1998,1998-02-22 11:00:00,1998-02-06 23:00:00,Japan,Nagano 1998,Winter,1998
32,oslo-1952,1952-02-25 19:00:00,1952-02-14 07:00:00,Norway,Oslo 1952,Winter,1952
33,paris-1900,1900-10-28 19:50:39,1900-05-14 08:50:39,France,Paris 1900,Summer,1900
34,paris-1924,1924-07-27 19:00:00,1924-05-04 07:00:00,France,Paris 1924,Summer,1924
35,pyeongchang-2018,2018-02-25 08:00:00,2018-02-08 23:00:00,Republic of Korea,PyeongChang 2018,Winter,2018
36,rio-2016,2016-08-21 21:00:00,2016-08-05 12:00:00,Brazil,Rio 2016,Summer,2016
37,rome-1960,1960-09-11 19:00:00,1960-08-25 07:00:00,Italy,Rome 1960,Summer,1960
38,salt-lake-city-2002,2002-02-24 08:00:00,2002-02-08 15:00:00,United States,Salt Lake City 2002,Winter,2002
39,sapporo-1972,1972-02-13 11:00:00,1972-02-02 23:00:00,Japan,Sapporo 1972,Winter,1972
40,sarajevo-1984,1984-02-19 19:00:00,1984-02-08 07:00:00,Yugoslavia,Sarajevo 1984,Winter,1984
41,seoul-1988,1988-10-02 10:00:00,1988-09-16 22:00:00,Republic of Korea,Seoul 1988,Summer,1988
42,sochi-2014,2014-02-23 16:00:00,2014-02-07 04:00:00,Russian Federation,Sochi 2014,Winter,2014
43,squaw-valley-1960,1960-02-28 04:00:00,1960-02-18 16:00:00,United States,Squaw Valley 1960,Winter,1960
44,st-louis-1904,1904-11-24 02:00:00,1904-07-01 14:00:00,United States,St. Louis 1904,Summer,1904
45,st-moritz-1928,1928-02-19 08:00:00,1928-02-11 08:00:00,Switzerland,St. Moritz 1928,Winter,1928
46,st-moritz-1948,1948-02-08 19:00:00,1948-01-30 07:00:00,Switzerland,St. Moritz 1948,Winter,1948
47,stockholm-1912,1912-07-27 20:00:00,1912-05-05 08:00:00,Sweden,Stockholm 1912,Summer,1912
48,sydney-2000,2000-10-01 09:00:00,2000-09-15 01:00:00,Australia,Sydney 2000,Summer,2000
49,tokyo-1964,1964-10-24 11:00:00,1964-10-09 23:00:00,Japan,Tokyo 1964,Summer,1964
50,tokyo-2020,2021-08-08 14:00:00,2021-07-23 11:00:00,Japan,Tokyo 2020,Summer,2020
51,turin-2006,2006-02-26 19:00:00,2006-02-10 07:00:00,Italy,Turin 2006,Winter,2006
52,vancouver-2010,2010-02-28 04:00:00,2010-02-12 16:00:00,Canada,Vancouver 2010,Winter,2010

In [3]:
df_hosts.dtypes

game_slug                  object
game_end_date      datetime64[ns]
game_start_date    datetime64[ns]
game_location              object
game_name                  object
game_season                object
game_year                   int64
dtype: object

In [4]:
# prendre que les Jo Ã©tÃ©
df_hosts = df_hosts.loc[df_hosts['game_season'] == 'Summer']

In [5]:
# Merge the tables on specified keys with suffixes to identify similar columns
merged_df = pd.merge(df_results, df_medals, 
                     on=['discipline_title', 'event_title', 'athlete_url', 'slug_game'], 
                     how='left',
                     suffixes=('', '_drop'))

# Remove duplicate columns by filtering out columns with '_drop' suffix
merged_df = merged_df[[c for c in merged_df.columns if not c.endswith('_drop')]]

for column in merged_df.columns:
    merged_df[column].fillna('None', inplace=True)

# Display the cleaned merged DataFrame
print(merged_df.head())

   id discipline_title    event_title     slug_game participant_type
0   1          Curling  Mixed Doubles  beijing-2022         GameTeam  \
1   2          Curling  Mixed Doubles  beijing-2022         GameTeam
2   3          Curling  Mixed Doubles  beijing-2022         GameTeam
3   4          Curling  Mixed Doubles  beijing-2022         GameTeam
4   5          Curling  Mixed Doubles  beijing-2022         GameTeam

  medal_type rank_equal rank_position   country_name country_code  ...
0       GOLD          0             1          Italy           IT  ...  \
1     SILVER          0             2         Norway           NO  ...
2     BRONZE          0             3         Sweden           SE  ...
3       None          0             4  Great Britain           GB  ...
4       None          0             5         Canada           CA  ...

                                         athlete_url     athlete_full_name
0  https://olympics.com/en/athletes/stefania-cons...  Stefania CONSTANTINI  \
1  https://olympics.com/en/athletes/kristin-skaslien      Kristin SKASLIEN
2     https://olympics.com/en/athletes/almida-de-val         Almida DE VAL
3    https://olympics.com/en/athletes/jennifer-dodds        Jennifer DODDS
4      https://olympics.com/en/athletes/rachel-homan          Rachel HOMAN

  value_unit value_type    athlete_full_name1
0       None       None  Stefania CONSTANTINI  \
1       None       None      Kristin SKASLIEN
2       None       None         Almida DE VAL
3       None       None        Jennifer DODDS
4       None       None          Rachel HOMAN

                                        athlete_url1  athlete_full_name2
0  https://olympics.com/en/athletes/stefania-cons...        Amos MOSANER  \
1  https://olympics.com/en/athletes/kristin-skaslien  Magnus NEDREGOTTEN
2     https://olympics.com/en/athletes/almida-de-val      Oskar ERIKSSON
3    https://olympics.com/en/athletes/jennifer-dodds         Bruce MOUAT
4      https://olympics.com/en/athletes/rachel-homan         John MORRIS

                                        athlete_url2 event_gender
0      https://olympics.com/en/athletes/amos-mosaner        Mixed  \
1  https://olympics.com/en/athletes/magnus-nedreg...        Mixed
2    https://olympics.com/en/athletes/oskar-eriksson        Mixed
3       https://olympics.com/en/athletes/bruce-mouat         None
4       https://olympics.com/en/athletes/john-morris         None

  participant_title
0             Italy
1            Norway
2            Sweden
3              None
4              None

[5 rows x 21 columns]

In [6]:
df_hosts.rename(columns={'game_slug': 'slug_game'}, inplace=True)
merged_df = pd.merge(df_results, df_hosts, left_on='slug_game', right_on='slug_game', how='left', suffixes=('', '_drop'))
for column in merged_df.columns:
    merged_df[column].fillna('None', inplace=True)
merged_df = merged_df.loc[merged_df['game_year'] != 'None']
# Remove duplicate columns by filtering out columns with '_drop' suffix
merged_df = merged_df[[c for c in merged_df.columns if not c.endswith('_drop')]]

## Nombre de mÃ©daille dâ€™Or, dâ€™Argent et de Bronze qui seront gagnÃ© par la France ?

In [7]:
merged_df

,id,discipline_title,event_title,slug_game,participant_type,medal_type,rank_equal,rank_position,country_name,country_code,...,athlete_full_name1,athlete_url1,athlete_full_name2,athlete_url2,game_end_date,game_start_date,game_location,game_name,game_season,game_year
3493,3785,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,GOLD,0,1,Spain,ES,...,Fatima GALVEZ,https://olympics.com/en/athletes/fatima-galvez,Alberto FERNANDEZ,https://olympics.com/en/athletes/alberto-ferna...,2021-08-08 14:00:00,2021-07-23 11:00:00,Japan,Tokyo 2020,Summer,2020.0
3494,3786,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,SILVER,0,2,San Marino,SM,...,Alessandra PERILLI,https://olympics.com/en/athletes/alessandra-pe...,Gian Marco BERTI,https://olympics.com/en/athletes/gian-marco-berti,2021-08-08 14:00:00,2021-07-23 11:00:00,Japan,Tokyo 2020,Summer,2020.0
3495,3787,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,BRONZE,0,3,United States of America,US,...,Madelynn Ann BERNAU,https://olympics.com/en/athletes/madelynn-ann-...,Brian BURROWS,https://olympics.com/en/athletes/brian-burrows,2021-08-08 14:00:00,2021-07-23 11:00:00,Japan,Tokyo 2020,Summer,2020.0
3496,3788,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,None,0,4,Slovakia,SK,...,Zuzana STEFECEKOVA,https://olympics.com/en/athletes/zuzana-stefec...,Erik VARGA,https://olympics.com/en/athletes/erik-varga,2021-08-08 14:00:00,2021-07-23 11:00:00,Japan,Tokyo 2020,Summer,2020.0
3497,3789,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,None,0,5,Japan,JP,...,Yukie NAKAYAMA,https://olympics.com/en/athletes/yukie-nakayama,Shigetaka OYAMA,https://olympics.com/en/athletes/shigetaka-oyama,2021-08-08 14:00:00,2021-07-23 11:00:00,Japan,Tokyo 2020,Summer,2020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146662,172623,Sailing,Â½-1 Ton Race Two Open,paris-1900,GameTeam,SILVER,None,None,France,FR,...,None,None,None,None,1900-10-28 19:50:39,1900-05-14 08:50:39,France,Paris 1900,Summer,1900.0
146663,172624,Archery,sur la perche Ã la herse men,paris-1900,Athlete,GOLD,None,None,Belgium,BE,...,None,None,None,None,1900-10-28 19:50:39,1900-05-14 08:50:39,France,Paris 1900,Summer,1900.0
146664,172625,Archery,sur la perche Ã la herse men,paris-1900,Athlete,SILVER,None,None,France,FR,...,None,None,None,None,1900-10-28 19:50:39,1900-05-14 08:50:39,France,Paris 1900,Summer,1900.0
146665,172626,Archery,sur la perche Ã la pyramide men,paris-1900,Athlete,GOLD,None,None,France,FR,...,None,None,None,None,1900-10-28 19:50:39,1900-05-14 08:50:39,France,Paris 1900,Summer,1900.0
146666,172627,Archery,sur la perche Ã la pyramide men,paris-1900,Athlete,SILVER,None,None,France,FR,...,None,None,None,None,1900-10-28 19:50:39,1900-05-14 08:50:39,France,Paris 1900,Summer,1900.0

In [8]:
merged_df = merged_df.loc[merged_df['medal_type'] != 'None']

In [9]:
merged_q1_df = merged_df[['game_year', 'game_location', 'country_name', 'medal_type']]
merged_q1_df = merged_q1_df.loc[merged_q1_df['country_name'] != 'None']

In [10]:
# Filter the DataFrame to include only the medal types of interest
# filtered_df = merged_q1_df[merged_q1_df['medal_type'].isin(['GOLD', 'SILVER', 'BRONZE'])]
# filtered_df = merged_q1_df['medal_type'].isin(['GOLD', 'SILVER', 'BRONZE'])
# Perform the grouping and count the number of each medal type for each combination of game_year and game_location
medal_counts = merged_q1_df.groupby(['game_year', 'game_location', 'country_name', 'medal_type']).size().unstack(fill_value=0)

# This will result in a DataFrame where each row represents a (game_year, game_location) combination,
# and columns represent counts for 'GOLD', 'SILVER', and 'BRONZE'.
medal_counts

medal_type                                        BRONZE  GOLD  SILVER
game_year game_location country_name
1896.0    Greece        Australia                      0     2       0
                        Austria                        2     2       1
                        Denmark                        3     1       2
                        France                         2     5       3
                        Germany                        2     4       4
...                                                  ...   ...     ...
2020.0    Japan         Uganda                         1     2       1
                        Ukraine                       14     1       7
                        United States of America      29    31      35
                        Uzbekistan                     2     3       0
                        Venezuela                      0     1       3

[1253 rows x 3 columns]

In [11]:
medal_counts_reset = medal_counts.reset_index()
# medal_counts_reset = medal_counts_reset.drop(medal_counts_reset.columns[0], axis=1)
medal_counts_reset

medal_type,game_year,game_location,country_name,BRONZE,GOLD,SILVER
0,1896.0,Greece,Australia,0,2,0
1,1896.0,Greece,Austria,2,2,1
2,1896.0,Greece,Denmark,3,1,2
3,1896.0,Greece,France,2,5,3
4,1896.0,Greece,Germany,2,4,4
...,...,...,...,...,...,...
1248,2020.0,Japan,Uganda,1,2,1
1249,2020.0,Japan,Ukraine,14,1,7
1250,2020.0,Japan,United States of America,29,31,35
1251,2020.0,Japan,Uzbekistan,2,3,0
1252,2020.0,Japan,Venezuela,0,1,3

In [12]:
# Assuming 'df' is your DataFrame
medal_counts_reset['game_year'] = medal_counts_reset['game_year'].astype(int)
medal_counts_reset['game_location'] = medal_counts_reset['game_location'].astype(str)
medal_counts_reset['country_name'] = medal_counts_reset['country_name'].astype(str)
medal_counts_reset.dtypes

medal_type
game_year         int32
game_location    object
country_name     object
BRONZE            int64
GOLD              int64
SILVER            int64
dtype: object

In [13]:
# Example using manual steps for preprocessing and model training
%pip install scikit-learn
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Data preparation
X = medal_counts_reset[['game_year', 'game_location', 'country_name']]
y = medal_counts_reset[['BRONZE', 'GOLD', 'SILVER']]
encoder = OneHotEncoder(handle_unknown='ignore')
X_encoded = encoder.fit_transform(X)

# Model training
model = RandomForestRegressor(n_estimators=100, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)

Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (1.5.0)
Requirement already satisfied: numpy>=1.19.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.6.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

RandomForestRegressor(random_state=42)

In [14]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Calculate mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# Calculate R-squared value
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 19.739461885790174
Mean Absolute Error: 2.5599203187250996
R-squared: 0.4994855659454309

In [28]:
import joblib

# Save the model
joblib.dump(model, 'medal_predictor_model.h5')
joblib.dump(encoder, 'encoder.h5')

['encoder.h5']

In [16]:
import joblib
import numpy as np

# Load the model
loaded_model = joblib.load('medal_predictor_model.h5')

# Preparing new data for prediction
new_data = pd.DataFrame({
    'game_year': [2022],
    'game_location': ['France'],  # Suppose 'France' was encoded as '8' in your original model
    'country_name': ['France']    # Suppose 'France' was encoded as '43' in your original model
})

# Encoding the new data using the same encoder used during training
new_data_encoded = encoder.transform(new_data)

# Predicting with the model
predictions = loaded_model.predict(new_data_encoded)
rounded_predictions = np.round(predictions).astype(int)
print("Predicted medal counts (Bronze, Gold, Silver):", rounded_predictions)

Predicted medal counts (Bronze, Gold, Silver): [[ 9 10 12]]

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(

In [17]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# # Encoder les variables catÃ©gorielles
# df_encoded_game_location = medal_counts_reset[['game_location']].drop_duplicates()
# df_encoded_game_location['game_location_encoded'] = le.fit_transform(df_encoded_game_location['game_location'])
# df_encoded_country_name = medal_counts_reset[['country_name']].drop_duplicates()
# df_encoded_country_name['country_name_encoded'] = le.fit_transform(df_encoded_country_name['country_name'])

In [18]:
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.pipeline import Pipeline

# from sklearn.model_selection import train_test_split
# import joblib

# # En supposant que 'medal_counts_reset' soit votre DataFrame
# X = medal_counts_reset[['game_year', 'game_location', 'country_name']]
# y = medal_counts_reset[['BRONZE', 'GOLD', 'SILVER']]

In [19]:
# # Remplacer les valeurs dans le DataFrame X
# X = medal_counts_reset[['game_year', 'game_location', 'country_name']]
# X = X.merge(df_encoded_game_location, on='game_location', how='left')
# X = X.merge(df_encoded_country_name, on='country_name', how='left')
# X['game_location'] = X['game_location_encoded']
# X['country_name'] = X['country_name_encoded']
# X = X.drop(['game_location_encoded', 'country_name_encoded'], axis=1)

In [20]:
# # Split data
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# print(X_train, y_train)
# X_train.dtypes

In [22]:
# # Initialize and train a random forest regressor
# model = RandomForestRegressor(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)

In [23]:
# from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# # Make predictions on the test data
# y_pred = model.predict(X_test)

# # Calculate mean squared error
# mse = mean_squared_error(y_test, y_pred)
# print("Mean Squared Error:", mse)

# # Calculate mean absolute error
# mae = mean_absolute_error(y_test, y_pred)
# print("Mean Absolute Error:", mae)

# # Calculate R-squared value
# r2 = r2_score(y_test, y_pred)
# print("R-squared:", r2)

In [24]:
# # Save the model to a file
# joblib.dump(model, 'medal_predictor_model1.h5')

In [25]:
# df_encoded_country_name

In [26]:
# df_encoded_game_location

In [27]:
import pandas as pd
import joblib
import numpy as np
from sklearn.pipeline import Pipeline
# # Example new data 
new_data = pd.DataFrame({
     'game_year': [2024],
     'game_location': [8],
     'country_name': [43]
})

# # Load the trained model pipeline
loaded_model = joblib.load('medal_predictor_model1.h5')

# # Predict using the model
predictions = loaded_model.predict(new_data)

# # Rounding the predictions to the nearest integer
rounded_predictions = np.round(predictions).astype(int)
print("Rounded predicted medal counts (Bronze, Gold, Silver):", rounded_predictions)

FileNotFoundError: [Errno 2] No such file or directory: 'medal_predictor_model1.h5'

# -----------------------------------------------------------------------------------------------------